---

- hosts: all
  become: true
  tasks:
   - name: install apache2 webserver and php package using apt
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
       update_cache: yes
     when: ansible_facts['distribution'] == "Ubuntu"

   - name: install apache2 webserver and php package using dnf
     yum:
       name:
         - httpd
         - php
       state: latest
       update_cache: yes
     when: ansible_facts['distribution'] == "CentOS"
