---

- hosts: all
  become: true
  tasks:

  - name: update repository cache (CentOS)
    when: ansible_distribution == "CentOS"
    tags: always
    yum:
      update_cache: yes
    changed_when: false

  - name: update repository cache (Ubuntu)
    when: ansible_distribution == "Ubuntu"
    tags: always
    apt:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
