---

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    when: ansible_distribution == "CentOS"
    tags: always
    yum:
      update_only: yes
      update_cache: yes

  - name: install updates (Ubuntu)
    when: ansible_distribution == "Ubuntu"
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 webserver and php package using apt
    when: ansible_facts['distribution'] == "Ubuntu"
    tags: apache, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb in database servers
    when: ansible_distribution == "CentOS"
    tags: db,centos,mariadb
    yum:
      name:
        - mariadb
      state: latest
