- name: install apache2 webserver and php package using apt
  when: ansible_distribution == "Ubuntu"
  tags: apache, ubuntu
  package:
    name:
      - "{{ web_package }}"
      - "{{ php_package }}"
    state: latest

- name: install httpd webserver and php package using yum
  when: ansible_distribution == "CentOS"
  tags: httpd, centos
  package:
    name:
      - "{{ web_package }}"
      - "{{ php_package }}"
    state: latest

- name: start web service in CentOS, not necessay for Ubuntu, apache2 serice starts automatically
  when: ansible_distribution == "CentOS"
  tags: httpd, centos
  service:
    name: "{{ web_service }}"
    state: started
    enabled: true

- name: change a line in httpd.conf using lineinfile module
  when: ansible_distribution == "CentOS"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: "ServerAdmin ready123.click"
  notify: restart_httpd

- name: copy site1.html as index.html
  tags: apache,apache2, httpd
  copy:
    src: site1.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: copy css1.css as css1.css
  tags: apache,apache2, httpd,css
  copy:
    src: css1.css
    dest: /var/www/html/css1.css
    owner: root
    group: root
    mode: 0644
