- name: install apache2 webserver and php package using apt
  when: ansible_distribution == "Ubuntu"
  tags: apache, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest

- name: install httpd webserver and php package using yum
  when: ansible_distribution == "CentOS"
  tags: httpd, centos
  yum:
    name:
      - httpd
      - php
    state: latest

- name: start web service in CentOS
  when: ansible_distribution == "CentOS"
  tags: httpd, centos
  service:
    name: httpd
    state: started
    enabled: true

- name: change a line in httpd.conf using lineinfile module
  when: ansible_distribution == "CentOS"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: "ServerAdmin ready123.net"
  register: httpdconf

- name: restart httpd based on a chnage in registered variable httpd.conf-change
  when: httpdconf.changed
  service:
    name: httpd
    state: restarted

- name: copy site1.html as index.html
  tags: apache,apache2, httpd
  copy:
    src: site1.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: copy css1.css as css1.css
  tags: apache,apache2, httpd,css
  copy:
    src: css1.css
    dest: /var/www/html/css1.css
    owner: root
    group: root
    mode: 0644

- name: add sudoers file for hurling user
  copy:
    src: sudoer_hurling
    dest: /etc/sudoers.d/hurling
    owner: root
    group: root
    mode: 0440
